name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: poteat/lean-workflows/.github/workflows/docs.yml@main
    with:
      package-name: bytes
      docs-targets: Bytes:docs BytesTheorems:docs
      landing-page: Bytes.html
      header-title: '<a href="https://code.lol/">code.lol</a> / bytes'
