name: Docs

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docs:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: poteat/lean-workflows/.github/workflows/docs.yml@main
    with:
      package-name: bytes
      docs-targets: Bytes:docs
      landing-page: Bytes.html
